### ISSUE TITLE
Just couldn't make this work

### ISSUE THREAD

**Issue by srqwebguy1** [ModernLMS/moodle-availability_othercompleted#28]
We have over 60 courses that need to be completed before a final exam is made available to students. We tried this plugin, and it just did not work for us. Even only listing one required course be completed didn't work. Even with full completion, the activity would not show to the user. Has this been a known issue? We are running Moodle 4.1

**Comment by sam-suresh** [comment]
Updated to Moodle 4.1 and 4.2

**Comment by srqwebguy1** [comment]
I updated the plug-in, and unfortunately, it still will not work for me. Appreciate any insight as to what might be wrong.
[Moodle][4.1.2+ (Build: 20230328)]


Restriction by other course completion | 2022092700
availability_othercompleted | 2023050310
